baseURL = "https://lufazol.github.io"
title = "SECOMP 2022"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = '<img height="300" src="/images/logotransparente2.png" alt="Logo"/>'
#fancyTitle = '<img height="400" src="/images/logotransparentepng.png" alt="Logo"/><br />' # title for frontpage, may include image
copyright = "SECOMP"
description = '12ª semana da computação da UNICAMP'
startbuttonText = ""
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/inscricoes/'
title = "Inscrições"

[[params.menu.main]]
url = '/palestraseatividades/'
title = "Palestras e atividades"

[[params.menu.main]]
url = '/empresasparceiras/'
title = "Empresas parceiras"

[[params.menu.main]]
url = '/cronograma/'
title = "Cronograma"

[[params.menu.main]]
url = '/premios/'
title = "Prêmios"

[[params.menu.main]]
url = '/organizacao/'
title = "Organização"

[[params.menu.main]]
url = '/localizacaoecontato/'
title = "Localização e contato"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'secomp 2022: novas realidades de 7 a 11 de novembro'
body = '''
Tendo como ponto de partida os crescentes debates e indagações sobre metaverso, é com muito entusiasmo que a organização da SECOMP 2022 
busca trazer discussões sobre as possíveis realidades arquitetadas não só pelo metaverso, mas também por outras novas tecnologias -- e isso sem deixar 
de lado todas as outras pautas sobre Computação que já temos o costume de acompanhar nos últimos anos, claro! ;)
'''

[[params.one.icon]]
icon = "fa-code"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-code"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two] 
enable = true

[[params.two.section]]
img = "images/dalle2.png"
title = 'Realidade aumentada, realidade virtual. Inteligência artificial, computação paralela, web 3.0. Blockchain, criptomoedas.'
body = 'Apesar de essas palavras estarem circulando entre nós já há algum tempo, as tecnologias que representam ainda despertam o interesse e a curiosidade de muita gente. A SECOMP 2022 está aqui para te ajudar a entendê-las melhor e para mostrar aonde poderão nos levar.'

[[params.two.section]]
img = "images/dalle3.png"
title = '"Sempre que uma vela é acesa,<br>cria-se também uma sombra."<br>Ursula K. Le Guin'
body = 'Com novas tecnologias e possibilidades, são criados também novos desafios e, possivelmente, problemas. Isso não nos escapou: queremos não apenas entender como funcionam essas novas realidades, mas todos os impactos que terão na sociedade. Nesse sentido, o papel de estudantes e profissionais da Computação é essencial para garantir que essas tecnologias sejam usadas da maneira mais benéfica e justa possível para toda a sociedade, de modo a diminuir diferenças e melhorar a qualidade de vida de toda a população -- e não apenas para uma parcela restrita.'

[params.three]
enable = true
title = 'Se prepara, porque vem aí:'

[[params.three.feature]]
icon = "fa-suitcase"
title = "Kits SECOMP 2022"
body = "Nesse ano teremos kits com camisetas, kits com canecas e kits com diversos outros brindes. Quanto mais você participar dos eventos da semana, mais chances de ganhar o seu kit SECOMP 2022!"

[[params.three.feature]]
icon = "fa-trophy"
title = "Prêmios e sorteios em todas as palestras e workshops"
body = "É exatamente isso que você leu: ao fim de toda palestra e workshop da SECOMP, além do sorteio de kits SECOMP 2022, sortearemos também prêmios."

[[params.three.feature]]
icon = "fa-coffee"
title = "(Muitos) coffee-breaks"
body = "Ninguém consegue aprender bem de estômago vazio, sabemos bem disso. Então, não se preocupa, que o que não vai faltar durante a semana é coffee-break de manhã, tarde e noite."

[[params.three.feature]]
icon = "fa-briefcase"
title = "Enterprise Day? Temos!"
body = "Como se a oportunidade de aprender um monte sobre Computação e tecnologias não fosse suficiente, também teremos dia e horário reservados para nossas empresas parceiras falarem dos (temidos) processos seletivos e compartilharem suas oportunidades."

[params.cta]
enable = true
title = "É hora de participar!"
body = "Não há taxa para participar e preencher o Forms de inscrição não toma nem 5 minutinhos. Se inscrevendo, suas chances de ganhar prêmios aumentam muito."

[[params.cta.link]]
href = "#"
text = "Cronograma"
special = false

[[params.cta.link]]
href = "#"
text = "Inscrição"
special = true

[params.contact]
enable = true
title = "Contato"
body = "Dúvidas? Pode mandar mensagem! :)"
phone = ""
address = ""
email = "secomp2022unicamp@gmail.com"
subject = "[Contato-site] Dúvida recebida!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
