baseURL = "https://lufazol.github.io"
title = "SECOMP 2022"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = '<img height="300" src="/images/logotransparente2.png" alt="Logo"/>'
#fancyTitle = '<img height="400" src="/images/logotransparentepng.png" alt="Logo"/><br />' # title for frontpage, may include image
copyright = "SECOMP"
description = '12ª semana da computação da UNICAMP'
startbuttonText = ""
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/inscricoes/'
title = "Inscrições"

[[params.menu.main]]
url = '/programacao/'
title = "Programação"

[[params.menu.main]]
url = '/localizacao/'
title = "Localização"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'secomp 2022: novas realidades'
body = '''
De 7 a 11 de novembro, no Instituto de Computação da UNICAMP, mais uma edição de uma das maiores semanas de computação do Brasil -- e de volta ao presencial.
'''

[[params.one.icon]]
icon = "fa-code"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-desktop"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two] 
enable = true

[[params.two.section]]
img = "images/dalle2.png"
title = 'Das conexões constantes ao metaverso'
body = '20 anos ou mesmo 10 anos atrás, era difícil prever o peso que a tecnologia e as conexões criadas por redes (sociais ou não) teriam no nosso dia a dia -- e quão insistentes e constantes elas se tornariam. Agora começamos a falar sobre novas realidades -- aumentadas, virtuais -- e metaverso, ao mesmo tempo em que tópicos como Inteligência Artificial e moedas virtuais têm ganhado cada vez mais espaço, não sem contestação ou polêmicas, como possíveis trilhas entre o ontem e o amanhã. Apesar de todas essas palavras estarem circulando entre nós já há algum tempo, as tecnologias que representam ainda despertam o interesse e a curiosidade de muita gente. A SECOMP 2022 está aqui para te ajudar a entendê-las melhor e para mostrar aonde poderão nos levar -- e os cuidados que devemos tomar.'

[[params.two.section]]
img = "images/dalle3.png"
title = '"Sempre que uma vela é acesa,<br>cria-se também uma sombra."<br>Ursula K. Le Guin'
body = 'Com novas tecnologias e possibilidades, são criados também novos desafios e, possivelmente, problemas. Isso não nos escapou: queremos não apenas entender como funcionam essas novas realidades e ferramentas, mas todos os impactos que terão na sociedade. Nesse sentido, o papel de estudantes e profissionais da Computação é e será essencial para garantir que essas tecnologias sejam usadas da maneira mais benéfica e justa possível, de modo a diminuir diferenças e melhorar a qualidade de vida de toda a população -- e não apenas de uma parcela restrita.'

[params.three]
enable = true
title = 'E se prepara, porque vem aí:'

[[params.three.feature]]
icon = "fa-trophy"
title = "sorteios de kits e prêmios em todas as palestras e workshops"
body = "É exatamente isso que você leu: ao fim de toda palestra e workshop da SECOMP, além do sorteio de kits SECOMP 2022, sortearemos também prêmios."

[[params.three.feature]]
icon = "fa-suitcase"
title = "Kits SECOMP 2022"
body = "Nesse ano teremos camisetas, sacochilas e brindes fazendo parte do nosso kit. Quanto mais você participar dos eventos da semana, mais chances de ganhar o seu kit SECOMP 2022!"

[[params.three.feature]]
icon = "fa-coffee"
title = "(Muitos) coffee-breaks"
body = "Ninguém consegue aprender bem de estômago vazio, sabemos bem disso. Então, não se preocupa, que a gente garante coffee-break de manhã, tarde e noite."

[[params.three.feature]]
icon = "fa-briefcase"
title = "Oportunidades de emprego? Temos!"
body = "Também teremos dia e horário reservados para nossas empresas parceiras falarem dos processos seletivos e compartilharem suas oportunidades. Sim, é ele de novo: o Enterprise Day."

[params.cta]
enable = true
title = "É hora de participar!"
body = "Não há taxa para participar da SECOMP, e preencher o Forms de inscrição não toma nem 5 minutinhos. Se inscrevendo, suas chances de ganhar prêmios nos sorteios aumentam muito. Vai pro Forms que a gente explica."

[[params.cta.link]]
href = "/programacao/"
text = "Programação"
special = false

[[params.cta.link]]
href = "/inscricoes/"
text = "Inscrição"
special = true

[params.contact]
enable = true
title = "Contato"
body = "Dúvidas? Pode falar com a gente! :)"
phone = ""
address = ""
email = "secomp2022unicamp@gmail.com"
subject = "[Contato-site] Dúvida recebida!"
plain = false

[params.social]
twitter = ""
facebook = "secompunicamp"
instagram = "secompunicamp"
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
